[build]
	base = "./"
	publish = "./out"
	command = "next build && next export"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
from = "/drive"
to   = "https://drive.google.com/drive/folders/0B9NuyBv-nQkBSEJjUXJ6Xy16aXM?resourcekey=0-ZDVVcBWFpHKhKmvC8OXE4Q&usp=sharing"
