[build]
	base = "./"
	publish = "./out"
	command = "npm run export"

[[redirects]]
from = "/drive"
to   = "https://drive.google.com/drive/folders/0B9NuyBv-nQkBSEJjUXJ6Xy16aXM?resourcekey=0-ZDVVcBWFpHKhKmvC8OXE4Q&usp=sharing"
